'use client';
import Link from 'next/link';
import {formatTokenAmount} from '@/lib/format';
import {useI18n} from '@/components/i18n/locale-provider';
import {authorityApi as api, accessStorage, labels, type BrowserAuthorityController} from '@/hooks/use-browser-authority';
const button = 'border border-primary/40 bg-primary/10 px-3 py-2 text-xs font-mono text-primary disabled:cursor-not-allowed disabled:opacity-40';
const input = 'w-full border border-border bg-background px-3 py-2 text-xs';
export function AuthorityControls({controller}: {controller: BrowserAuthorityController}) {
  const {t} = useI18n();
  const {wallet, setWallet, access, setAccess, snapshot, setSnapshot, config, budget, setBudget, hours, setHours, busy, error, setError, reconcileHash, setReconcileHash, balances, setBalances, goal, setGoal, run, setRun, saveAccess, refresh, perform, sdkWallet, connect, executeStep, revoking, steps, nextStep, pending, active, loaded, startRun} = controller;
  return <div className="space-y-3 p-3 text-xs">
    <div><p className="widget-label">─ {t('authority.kicker')}</p><h1 className="mt-2 text-xs font-semibold">{t('authority.title')}</h1><p className="mt-2 text-muted-foreground">{t('authority.subtitle')}</p></div>
    <section className="border border-border bg-card p-3"><h2 className="widget-label mb-2">─ {t('authority.section.wallet')}</h2>
      {wallet ? <><p className="mt-3 break-all font-mono text-xs">{wallet.address}</p><p className="mt-2 text-xs text-muted-foreground">{t('authority.wallet.fundHint')}</p><div className="mt-4 flex flex-wrap gap-3"><button className={button} disabled={!!busy} onClick={() => void perform(t('authority.busy.checkingBalances'), async () => { const {client, wallet: w} = await sdkWallet(); const b = await client.balances({wallet: w, chainId: 97, tokens: config ? [config.token.address] : []}); const {formatEther, formatUnits} = await import('ethers'); setBalances(`${formatEther(b.native)} tBNB · ${b.tokens?.[0]?.ok ? formatUnits(b.tokens[0].raw, 18) : t('authority.unavailable')} U`); })}>{t('authority.wallet.checkBalance')}</button><a className="px-2 py-2 text-xs underline" href={`https://testnet.altana.network/account/${wallet.address}`} target="_blank" rel="noreferrer">{t('authority.wallet.explorer')}</a><a className="px-2 py-2 text-xs underline" href="https://testnet.bnbchain.org/faucet-smart" target="_blank" rel="noreferrer">{t('authority.wallet.faucet')}</a></div><p className="mt-3 font-mono text-xs">{balances}</p></> : <div className="mt-4 flex gap-3"><button className={button} disabled={!!busy} onClick={() => void perform(t('authority.busy.creatingWallet'), () => connect(false))}>{t('authority.wallet.create')}</button><button className={button} disabled={!!busy} onClick={() => void perform(t('authority.busy.recoveringWallet'), () => connect(true))}>{t('authority.wallet.recover')}</button></div>}
    </section>
    {snapshot?.authority.status === 'invalid' && !snapshot.authority.grantTxHash && <section className="border border-border bg-card p-3"><h2 className="widget-label mb-2">─ {t('authority.section.unfinished')}</h2><p className="mt-3 text-xs">{t('authority.unfinished.body')}</p><button className={`${button} mt-4`} disabled={!!busy} onClick={() => void perform(t('authority.busy.checkingUnregistered'), async () => { await api(`/${access!.id}/check-ungranted`, access, {}); sessionStorage.removeItem(accessStorage); setAccess(undefined); setSnapshot(undefined); setRun(undefined); setReconcileHash(''); setHours(2); })}>{t('authority.unfinished.action')}</button></section>}
    {snapshot?.authority.status === 'revoked' && <section className="border border-border bg-card p-3"><h2 className="widget-label mb-2">─ {t('authority.section.ready')}</h2><p className="mt-3 text-xs">{t('authority.ready.body')}</p><button className={`${button} mt-4`} disabled={!!busy} onClick={() => { sessionStorage.removeItem(accessStorage); setAccess(undefined); setSnapshot(undefined); setRun(undefined); setReconcileHash(''); setError(''); setHours(2); }}>{t('authority.ready.action')}</button></section>}
    <section className="border border-border bg-card p-3"><h2 className="widget-label mb-2">─ {t('authority.section.permissions')}</h2>
      {!snapshot ? <><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs">{t('authority.budgetLabel')}<input className={`${input} mt-2`} value={budget} onChange={(e) => setBudget(e.target.value)} inputMode="decimal" /></label><label className="text-xs">{t('authority.durationLabel')}<input className={`${input} mt-2`} value={hours} type="number" min={1} max={24} onChange={(e) => setHours(Number(e.target.value))}/></label></div><p className="mt-4 text-xs text-muted-foreground">{t('authority.recipientsHint')}</p><ul className="mt-2 space-y-1 break-all font-mono text-xs">{config?.recipients.map((a) => <li key={a}>{a}</li>)}</ul><button className={`${button} mt-5`} disabled={!!busy || !wallet || !config?.recipients.length} onClick={() => void perform(t('authority.busy.preparingSession'), async () => { const result = await api<NonNullable<BrowserAuthorityController['snapshot']> & {accessToken: string}>('/prepare', undefined, {walletAddress: wallet!.address, limit: budget, hours}); const a = {id: result.authority.authorityId, token: result.accessToken}; saveAccess(a); setSnapshot(result); await refresh(a); })}>{t('authority.prepare')}</button></> : <><p className="mt-3 text-xs">{t('authority.statusLabel')}: <strong>{snapshot.authority.status}</strong> · {t('authority.expires', {time: new Date(snapshot.authority.expiry * 1000).toLocaleString()})}</p><p className="mt-2 font-mono text-xs">{t('authority.budgetSummary', {limit: formatTokenAmount(snapshot.authority.spendLimits[0].limit, 18, 3), spent: snapshot.spending?.[0] ? formatTokenAmount(snapshot.spending[0].spent, 18, 3) : t('authority.unavailable')})}</p><p className="mt-2 text-xs">{t('authority.approveOnceHint')}</p><ol className="mt-5 space-y-3">{steps.map((step) => <li key={step} className="flex flex-wrap items-center justify-between gap-3 border border-border bg-card p-2 text-[11px]"><span>{snapshot.lifecycle?.transactions[step] ? '✓ ' : ''}{t(labels[step])}</span>{snapshot.lifecycle?.transactions[step] ? <a href={`https://testnet.bscscan.com/tx/${snapshot.lifecycle.transactions[step]}`} target="_blank" rel="noreferrer" className="underline">{t('authority.transaction')}</a> : <button className={button} disabled={!!busy || step !== nextStep || !!pending} onClick={() => void perform(t(labels[step]), () => executeStep(step))}>{t('authority.confirmOnDevice')}</button>}</li>)}</ol>
        {pending && <div className="mt-4 border border-amber-600/30 bg-card p-3"><p className="text-xs">{t('authority.pending.body', {label: t(labels[pending])})}</p><input aria-label={t('authority.pending.hashLabel')} className={`${input} mt-3`} placeholder="0x…" value={reconcileHash} onChange={(e) => setReconcileHash(e.target.value)} /><button className={`${button} mt-3`} disabled={!!busy} onClick={() => void perform(t('authority.busy.checkingTransaction'), async () => { await api(`/${access!.id}/confirm`, access, {transactionHash: reconcileHash || sessionStorage.getItem(`agora.pending-tx.${access!.id}`)}); await refresh(); })}>{t('authority.pending.verify')}</button></div>}
        <button className="mt-4 text-xs underline" disabled={!!busy} onClick={() => void perform(t('authority.busy.refreshing'), () => refresh())}>{t('authority.refresh')}</button>
      </>}
    </section>
    {snapshot && snapshot.authority.status !== 'revoked' && <section className="border border-destructive/30 bg-card p-3"><h2 className="widget-label mb-2">─ {t('authority.section.stop')}</h2><p className="mt-3 text-xs">{t('authority.stop.body')}</p>{!revoking ? <button className={`${button} mt-4`} disabled={!!busy} onClick={() => void perform(t('authority.busy.revokingSignatures'), () => executeStep('revokeChecker'))}>{t('authority.stop.start')}</button> : !nextStep && <button className={`${button} mt-4`} disabled={!!busy} onClick={() => void perform(t('authority.busy.verifyingRevoked'), async () => { await api(`/${access!.id}/finish-revoke`, access, {}); await refresh(); })}>{t('authority.stop.finish')}</button>}</section>}
    {snapshot?.revocation?.negativeTest?.rejected && <div className="border border-emerald-700/30 bg-card p-3 text-xs"><p>{t('authority.negative.body', {deleted: snapshot.revocation.sessionMaterialDeleted ? t('authority.yes') : t('authority.no')})}</p><button className={`${button} mt-4`} onClick={() => {sessionStorage.removeItem(accessStorage); setAccess(undefined); setSnapshot(undefined); setRun(undefined); setGoal('');}}>{t('authority.prepareAnother')}</button></div>}
    <div role="status" aria-live="polite" className="text-xs">{busy && <p>{busy}…</p>}{error && <p className="border border-destructive/30 p-3 text-destructive">{error}</p>}</div>
    <Link className="text-xs underline" href="/authority">{t('authority.inspectEvidence')}</Link>
  </div>;
}
