'use client';
import Link from 'next/link';
import {formatTokenAmount} from '@/lib/format';
import {authorityApi as api, accessStorage, labels, type BrowserAuthorityController} from '@/hooks/use-browser-authority';
const button = 'border border-primary/40 bg-primary/10 px-3 py-2 text-xs font-mono text-primary disabled:cursor-not-allowed disabled:opacity-40';
const input = 'w-full border border-border bg-background px-3 py-2 text-sm';
export function AuthorityControls({controller}: {controller: BrowserAuthorityController}) {
  const {wallet, setWallet, access, setAccess, snapshot, setSnapshot, config, budget, setBudget, hours, setHours, busy, error, setError, reconcileHash, setReconcileHash, balances, setBalances, goal, setGoal, run, setRun, saveAccess, refresh, perform, sdkWallet, connect, executeStep, revoking, steps, nextStep, pending, active, loaded, startRun} = controller;
  return <div className="space-y-4 p-4 text-sm">
    <div><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">BNB Testnet · Passkey wallet</p><h1 className="mt-3 font-heading text-xl font-semibold">Give Hunter a goal and a boundary.</h1><p className="mt-4 text-muted-foreground">Your device approves the budget. Hunter pays specialist agents within it.</p></div>
    <section className="rounded-none border border-border p-6"><h2 className="text-xl font-semibold">1. Your wallet</h2>
      {wallet ? <><p className="mt-3 break-all font-mono text-sm">{wallet.address}</p><p className="mt-2 text-sm text-muted-foreground">Fund this wallet with testnet BNB for fees and testnet U for services.</p><div className="mt-4 flex flex-wrap gap-3"><button className={button} disabled={!!busy} onClick={() => void perform('Checking balances', async () => { const {client, wallet: w} = await sdkWallet(); const b = await client.balances({wallet: w, chainId: 97, tokens: config ? [config.token.address] : []}); const {formatEther, formatUnits} = await import('ethers'); setBalances(`${formatEther(b.native)} tBNB · ${b.tokens?.[0]?.ok ? formatUnits(b.tokens[0].raw, 18) : 'unavailable'} U`); })}>Check balance</button><a className="px-2 py-2 text-sm underline" href={`https://testnet.altana.network/account/${wallet.address}`} target="_blank" rel="noreferrer">Altana Explorer</a><a className="px-2 py-2 text-sm underline" href="https://testnet.bnbchain.org/faucet-smart" target="_blank" rel="noreferrer">Testnet faucet</a></div><p className="mt-3 font-mono text-sm">{balances}</p></> : <div className="mt-4 flex gap-3"><button className={button} disabled={!!busy} onClick={() => void perform('Creating Passkey wallet', () => connect(false))}>Create Passkey wallet</button><button className={button} disabled={!!busy} onClick={() => void perform('Recovering wallet', () => connect(true))}>Recover with Passkey</button></div>}
    </section>
    {snapshot?.authority.status === 'invalid' && !snapshot.authority.grantTxHash && <section className="rounded-none border border-border p-6"><h2 className="text-xl font-semibold">Unfinished Authority</h2><p className="mt-3 text-sm">Check whether this session was never registered before setting up another. Existing evidence is retained.</p><button className={`${button} mt-4`} disabled={!!busy} onClick={() => void perform('Checking unregistered session', async () => { await api(`/${access!.id}/check-ungranted`, access, {}); sessionStorage.removeItem(accessStorage); setAccess(undefined); setSnapshot(undefined); setRun(undefined); setReconcileHash(''); setHours(2); })}>Check unregistered session and start again</button></section>}
    {snapshot?.authority.status === 'revoked' && <section className="rounded-none border border-border p-6"><h2 className="text-xl font-semibold">Ready for a new task</h2><p className="mt-3 text-sm">This Authority is revoked. Start a new bounded session with this Passkey wallet. Previous reports remain available.</p><button className={`${button} mt-4`} disabled={!!busy} onClick={() => { sessionStorage.removeItem(accessStorage); setAccess(undefined); setSnapshot(undefined); setRun(undefined); setReconcileHash(''); setError(''); setHours(2); }}>Set up a new Authority</button></section>}
    <section className="rounded-none border border-border p-6"><h2 className="text-xl font-semibold">2. Set permissions</h2>
      {!snapshot ? <><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm">Budget (testnet U)<input className={`${input} mt-2`} value={budget} onChange={(e) => setBudget(e.target.value)} inputMode="decimal" /></label><label className="text-sm">Duration (hours)<input className={`${input} mt-2`} value={hours} type="number" min={1} max={24} onChange={(e) => setHours(Number(e.target.value))}/></label></div><p className="mt-4 text-sm text-muted-foreground">Only these service recipients will be allowed:</p><ul className="mt-2 space-y-1 break-all font-mono text-xs">{config?.recipients.map((a) => <li key={a}>{a}</li>)}</ul><button className={`${button} mt-5`} disabled={!!busy || !wallet || !config?.recipients.length} onClick={() => void perform('Preparing session', async () => { const result = await api<NonNullable<BrowserAuthorityController['snapshot']> & {accessToken: string}>('/prepare', undefined, {walletAddress: wallet!.address, limit: budget, hours}); const a = {id: result.authority.authorityId, token: result.accessToken}; saveAccess(a); setSnapshot(result); await refresh(a); })}>Prepare bounded session</button></> : <><p className="mt-3 text-sm">Status: <strong>{snapshot.authority.status}</strong> · Expires {new Date(snapshot.authority.expiry * 1000).toLocaleString()}</p><p className="mt-2 font-mono text-sm">Budget: {formatTokenAmount(snapshot.authority.spendLimits[0].limit, 18, 3)} U · Confirmed spend: {snapshot.spending?.[0] ? formatTokenAmount(snapshot.spending[0].spent, 18, 3) : 'unavailable'} U</p><p className="mt-2 text-sm">The exact budget is approved once. Each step below requires your device confirmation.</p><ol className="mt-5 space-y-3">{steps.map((step) => <li key={step} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-secondary p-3 text-sm"><span>{snapshot.lifecycle?.transactions[step] ? '✓ ' : ''}{labels[step]}</span>{snapshot.lifecycle?.transactions[step] ? <a href={`https://testnet.bscscan.com/tx/${snapshot.lifecycle.transactions[step]}`} target="_blank" rel="noreferrer" className="underline">Transaction</a> : <button className={button} disabled={!!busy || step !== nextStep || !!pending} onClick={() => void perform(labels[step], () => executeStep(step))}>Confirm on device</button>}</li>)}</ol>
        {pending && <div className="mt-4 rounded-lg border border-amber-600/30 p-4"><p className="text-sm">{labels[pending]} is awaiting confirmation. Paste the transaction hash to check its onchain state before sending another transaction.</p><input aria-label="Transaction hash" className={`${input} mt-3`} placeholder="0x…" value={reconcileHash} onChange={(e) => setReconcileHash(e.target.value)} /><button className={`${button} mt-3`} disabled={!!busy} onClick={() => void perform('Checking transaction', async () => { await api(`/${access!.id}/confirm`, access, {transactionHash: reconcileHash || sessionStorage.getItem(`agora.pending-tx.${access!.id}`)}); await refresh(); })}>Verify transaction</button></div>}
        <button className="mt-4 text-sm underline" disabled={!!busy} onClick={() => void perform('Refreshing Authority', () => refresh())}>Refresh status</button>
      </>}
    </section>
    {snapshot && snapshot.authority.status !== 'revoked' && <section className="rounded-none border border-destructive/30 p-6"><h2 className="text-xl font-semibold">Stop Hunter spending</h2><p className="mt-3 text-sm">Revoke payment signatures, clear the U allowance, then revoke the session. Hunter is disabled locally before the first step.</p>{!revoking ? <button className={`${button} mt-4`} disabled={!!busy} onClick={() => void perform('Revoking payment signatures', () => executeStep('revokeChecker'))}>Start revocation</button> : !nextStep && <button className={`${button} mt-4`} disabled={!!busy} onClick={() => void perform('Verifying revoked key', async () => { await api(`/${access!.id}/finish-revoke`, access, {}); await refresh(); })}>Verify rejection and delete session key</button>}</section>}
    {snapshot?.revocation?.negativeTest?.rejected && <div className="rounded-none border border-emerald-700/30 p-5 text-sm"><p>Revoked Session payment was rejected. Session key deleted: {snapshot.revocation.sessionMaterialDeleted ? 'yes' : 'no'}.</p><button className={`${button} mt-4`} onClick={() => {sessionStorage.removeItem(accessStorage); setAccess(undefined); setSnapshot(undefined); setRun(undefined); setGoal('');}}>Prepare another bounded Authority</button></div>}
    <div role="status" aria-live="polite" className="text-sm">{busy && <p>{busy}…</p>}{error && <p className="rounded-none border border-destructive/30 p-4 text-destructive">{error}</p>}</div>
    <Link className="text-sm underline" href="/authority">Inspect historical Authority evidence</Link>
  </div>;
}
